// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serv.proto
// Protobuf C++ Version: 5.29.0

#include "serv.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace mid {

inline constexpr GenerateResponsePayoutPostman::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : uuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GenerateResponsePayoutPostman::GenerateResponsePayoutPostman(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GenerateResponsePayoutPostmanDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenerateResponsePayoutPostmanDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenerateResponsePayoutPostmanDefaultTypeInternal() {}
  union {
    GenerateResponsePayoutPostman _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenerateResponsePayoutPostmanDefaultTypeInternal _GenerateResponsePayoutPostman_default_instance_;

inline constexpr GenerateResponseInvoiceP2PPostman::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : uuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        card_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cardholdername_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        bankname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sum_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GenerateResponseInvoiceP2PPostman::GenerateResponseInvoiceP2PPostman(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GenerateResponseInvoiceP2PPostmanDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenerateResponseInvoiceP2PPostmanDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenerateResponseInvoiceP2PPostmanDefaultTypeInternal() {}
  union {
    GenerateResponseInvoiceP2PPostman _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenerateResponseInvoiceP2PPostmanDefaultTypeInternal _GenerateResponseInvoiceP2PPostman_default_instance_;

inline constexpr GenerateRequestPayoutPostman::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : card_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ordertype_{static_cast< ::mid::OrderType >(0)},
        sum_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GenerateRequestPayoutPostman::GenerateRequestPayoutPostman(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GenerateRequestPayoutPostmanDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenerateRequestPayoutPostmanDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenerateRequestPayoutPostmanDefaultTypeInternal() {}
  union {
    GenerateRequestPayoutPostman _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenerateRequestPayoutPostmanDefaultTypeInternal _GenerateRequestPayoutPostman_default_instance_;

inline constexpr GenerateRequestP2PPostman::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ordertype_{static_cast< ::mid::OrderType >(0)},
        sum_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GenerateRequestP2PPostman::GenerateRequestP2PPostman(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GenerateRequestP2PPostmanDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenerateRequestP2PPostmanDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenerateRequestP2PPostmanDefaultTypeInternal() {}
  union {
    GenerateRequestP2PPostman _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenerateRequestP2PPostmanDefaultTypeInternal _GenerateRequestP2PPostman_default_instance_;

inline constexpr GenerateInvoiceResponseFPSPostman::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : uuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        card_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cardholdername_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        bankname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sum_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GenerateInvoiceResponseFPSPostman::GenerateInvoiceResponseFPSPostman(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GenerateInvoiceResponseFPSPostmanDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenerateInvoiceResponseFPSPostmanDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenerateInvoiceResponseFPSPostmanDefaultTypeInternal() {}
  union {
    GenerateInvoiceResponseFPSPostman _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenerateInvoiceResponseFPSPostmanDefaultTypeInternal _GenerateInvoiceResponseFPSPostman_default_instance_;

inline constexpr GenerateInvoiceRequestFPSPostman::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ordertype_{static_cast< ::mid::OrderType >(0)},
        sum_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GenerateInvoiceRequestFPSPostman::GenerateInvoiceRequestFPSPostman(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GenerateInvoiceRequestFPSPostmanDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenerateInvoiceRequestFPSPostmanDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenerateInvoiceRequestFPSPostmanDefaultTypeInternal() {}
  union {
    GenerateInvoiceRequestFPSPostman _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenerateInvoiceRequestFPSPostmanDefaultTypeInternal _GenerateInvoiceRequestFPSPostman_default_instance_;
}  // namespace mid
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_serv_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_serv_2eproto = nullptr;
const ::uint32_t
    TableStruct_serv_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::mid::GenerateRequestP2PPostman, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mid::GenerateRequestP2PPostman, _impl_.ordertype_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateRequestP2PPostman, _impl_.sum_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::mid::GenerateResponseInvoiceP2PPostman, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mid::GenerateResponseInvoiceP2PPostman, _impl_.uuid_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateResponseInvoiceP2PPostman, _impl_.card_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateResponseInvoiceP2PPostman, _impl_.sum_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateResponseInvoiceP2PPostman, _impl_.cardholdername_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateResponseInvoiceP2PPostman, _impl_.bankname_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::mid::GenerateInvoiceRequestFPSPostman, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mid::GenerateInvoiceRequestFPSPostman, _impl_.ordertype_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateInvoiceRequestFPSPostman, _impl_.sum_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::mid::GenerateInvoiceResponseFPSPostman, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mid::GenerateInvoiceResponseFPSPostman, _impl_.uuid_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateInvoiceResponseFPSPostman, _impl_.card_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateInvoiceResponseFPSPostman, _impl_.sum_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateInvoiceResponseFPSPostman, _impl_.cardholdername_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateInvoiceResponseFPSPostman, _impl_.bankname_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::mid::GenerateRequestPayoutPostman, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mid::GenerateRequestPayoutPostman, _impl_.ordertype_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateRequestPayoutPostman, _impl_.sum_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateRequestPayoutPostman, _impl_.card_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::mid::GenerateResponsePayoutPostman, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::mid::GenerateResponsePayoutPostman, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateResponsePayoutPostman, _impl_.uuid_),
        PROTOBUF_FIELD_OFFSET(::mid::GenerateResponsePayoutPostman, _impl_.success_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::mid::GenerateRequestP2PPostman)},
        {10, -1, -1, sizeof(::mid::GenerateResponseInvoiceP2PPostman)},
        {23, -1, -1, sizeof(::mid::GenerateInvoiceRequestFPSPostman)},
        {33, -1, -1, sizeof(::mid::GenerateInvoiceResponseFPSPostman)},
        {46, -1, -1, sizeof(::mid::GenerateRequestPayoutPostman)},
        {57, -1, -1, sizeof(::mid::GenerateResponsePayoutPostman)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::mid::_GenerateRequestP2PPostman_default_instance_._instance,
    &::mid::_GenerateResponseInvoiceP2PPostman_default_instance_._instance,
    &::mid::_GenerateInvoiceRequestFPSPostman_default_instance_._instance,
    &::mid::_GenerateInvoiceResponseFPSPostman_default_instance_._instance,
    &::mid::_GenerateRequestPayoutPostman_default_instance_._instance,
    &::mid::_GenerateResponsePayoutPostman_default_instance_._instance,
};
const char descriptor_table_protodef_serv_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nserv.proto\022\003mid\"K\n\031GenerateRequestP2PP"
    "ostman\022!\n\torderType\030\001 \001(\0162\016.mid.OrderTyp"
    "e\022\013\n\003Sum\030\002 \001(\005\"v\n!GenerateResponseInvoic"
    "eP2PPostman\022\014\n\004Uuid\030\001 \001(\t\022\014\n\004Card\030\002 \001(\t\022"
    "\013\n\003Sum\030\003 \001(\005\022\026\n\016CardHolderName\030\004 \001(\t\022\020\n\010"
    "BankName\030\005 \001(\t\"R\n GenerateInvoiceRequest"
    "FPSPostman\022!\n\torderType\030\001 \001(\0162\016.mid.Orde"
    "rType\022\013\n\003Sum\030\002 \001(\005\"v\n!GenerateInvoiceRes"
    "ponseFPSPostman\022\014\n\004Uuid\030\001 \001(\t\022\014\n\004Card\030\002 "
    "\001(\t\022\013\n\003Sum\030\003 \001(\005\022\026\n\016CardHolderName\030\004 \001(\t"
    "\022\020\n\010BankName\030\005 \001(\t\"\\\n\034GenerateRequestPay"
    "outPostman\022!\n\torderType\030\001 \001(\0162\016.mid.Orde"
    "rType\022\013\n\003sum\030\002 \001(\005\022\014\n\004card\030\003 \001(\t\"J\n\035Gene"
    "rateResponsePayoutPostman\022\n\n\002id\030\001 \001(\005\022\014\n"
    "\004uuid\030\002 \001(\t\022\017\n\007success\030\003 \001(\010**\n\tOrderTyp"
    "e\022\013\n\007UNKNOWN\020\000\022\007\n\003P2P\020\001\022\007\n\003FPS\020\0022\241\002\n\003Api"
    "\022\\\n\022GenerateInvoiceP2P\022\036.mid.GenerateReq"
    "uestP2PPostman\032&.mid.GenerateResponseInv"
    "oiceP2PPostman\022c\n\022GenerateInvoiceFPS\022%.m"
    "id.GenerateInvoiceRequestFPSPostman\032&.mi"
    "d.GenerateInvoiceResponseFPSPostman\022W\n\016G"
    "eneratePayout\022!.mid.GenerateRequestPayou"
    "tPostman\032\".mid.GenerateResponsePayoutPos"
    "tmanB\021Z\017protoFile/filesb\006proto3"
};
static ::absl::once_flag descriptor_table_serv_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_serv_2eproto = {
    false,
    false,
    951,
    descriptor_table_protodef_serv_2eproto,
    "serv.proto",
    &descriptor_table_serv_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_serv_2eproto::offsets,
    file_level_enum_descriptors_serv_2eproto,
    file_level_service_descriptors_serv_2eproto,
};
namespace mid {
const ::google::protobuf::EnumDescriptor* OrderType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_serv_2eproto);
  return file_level_enum_descriptors_serv_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t OrderType_internal_data_[] = {
    196608u, 0u, };
bool OrderType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class GenerateRequestP2PPostman::_Internal {
 public:
};

GenerateRequestP2PPostman::GenerateRequestP2PPostman(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mid.GenerateRequestP2PPostman)
}
GenerateRequestP2PPostman::GenerateRequestP2PPostman(
    ::google::protobuf::Arena* arena, const GenerateRequestP2PPostman& from)
    : GenerateRequestP2PPostman(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GenerateRequestP2PPostman::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GenerateRequestP2PPostman::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ordertype_),
           0,
           offsetof(Impl_, sum_) -
               offsetof(Impl_, ordertype_) +
               sizeof(Impl_::sum_));
}
GenerateRequestP2PPostman::~GenerateRequestP2PPostman() {
  // @@protoc_insertion_point(destructor:mid.GenerateRequestP2PPostman)
  SharedDtor(*this);
}
inline void GenerateRequestP2PPostman::SharedDtor(MessageLite& self) {
  GenerateRequestP2PPostman& this_ = static_cast<GenerateRequestP2PPostman&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* GenerateRequestP2PPostman::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GenerateRequestP2PPostman(arena);
}
constexpr auto GenerateRequestP2PPostman::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GenerateRequestP2PPostman),
                                            alignof(GenerateRequestP2PPostman));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GenerateRequestP2PPostman::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GenerateRequestP2PPostman_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GenerateRequestP2PPostman::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GenerateRequestP2PPostman>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GenerateRequestP2PPostman::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GenerateRequestP2PPostman>(), &GenerateRequestP2PPostman::ByteSizeLong,
            &GenerateRequestP2PPostman::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GenerateRequestP2PPostman, _impl_._cached_size_),
        false,
    },
    &GenerateRequestP2PPostman::kDescriptorMethods,
    &descriptor_table_serv_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GenerateRequestP2PPostman::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> GenerateRequestP2PPostman::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mid::GenerateRequestP2PPostman>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 Sum = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GenerateRequestP2PPostman, _impl_.sum_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateRequestP2PPostman, _impl_.sum_)}},
    // .mid.OrderType orderType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GenerateRequestP2PPostman, _impl_.ordertype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateRequestP2PPostman, _impl_.ordertype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .mid.OrderType orderType = 1;
    {PROTOBUF_FIELD_OFFSET(GenerateRequestP2PPostman, _impl_.ordertype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 Sum = 2;
    {PROTOBUF_FIELD_OFFSET(GenerateRequestP2PPostman, _impl_.sum_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GenerateRequestP2PPostman::Clear() {
// @@protoc_insertion_point(message_clear_start:mid.GenerateRequestP2PPostman)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.ordertype_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.sum_) -
      reinterpret_cast<char*>(&_impl_.ordertype_)) + sizeof(_impl_.sum_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GenerateRequestP2PPostman::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GenerateRequestP2PPostman& this_ = static_cast<const GenerateRequestP2PPostman&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GenerateRequestP2PPostman::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GenerateRequestP2PPostman& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:mid.GenerateRequestP2PPostman)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .mid.OrderType orderType = 1;
          if (this_._internal_ordertype() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_ordertype(), target);
          }

          // int32 Sum = 2;
          if (this_._internal_sum() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_sum(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:mid.GenerateRequestP2PPostman)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GenerateRequestP2PPostman::ByteSizeLong(const MessageLite& base) {
          const GenerateRequestP2PPostman& this_ = static_cast<const GenerateRequestP2PPostman&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GenerateRequestP2PPostman::ByteSizeLong() const {
          const GenerateRequestP2PPostman& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:mid.GenerateRequestP2PPostman)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .mid.OrderType orderType = 1;
            if (this_._internal_ordertype() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_ordertype());
            }
            // int32 Sum = 2;
            if (this_._internal_sum() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_sum());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GenerateRequestP2PPostman::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GenerateRequestP2PPostman*>(&to_msg);
  auto& from = static_cast<const GenerateRequestP2PPostman&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mid.GenerateRequestP2PPostman)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ordertype() != 0) {
    _this->_impl_.ordertype_ = from._impl_.ordertype_;
  }
  if (from._internal_sum() != 0) {
    _this->_impl_.sum_ = from._impl_.sum_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GenerateRequestP2PPostman::CopyFrom(const GenerateRequestP2PPostman& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mid.GenerateRequestP2PPostman)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GenerateRequestP2PPostman::InternalSwap(GenerateRequestP2PPostman* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GenerateRequestP2PPostman, _impl_.sum_)
      + sizeof(GenerateRequestP2PPostman::_impl_.sum_)
      - PROTOBUF_FIELD_OFFSET(GenerateRequestP2PPostman, _impl_.ordertype_)>(
          reinterpret_cast<char*>(&_impl_.ordertype_),
          reinterpret_cast<char*>(&other->_impl_.ordertype_));
}

::google::protobuf::Metadata GenerateRequestP2PPostman::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GenerateResponseInvoiceP2PPostman::_Internal {
 public:
};

GenerateResponseInvoiceP2PPostman::GenerateResponseInvoiceP2PPostman(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mid.GenerateResponseInvoiceP2PPostman)
}
inline PROTOBUF_NDEBUG_INLINE GenerateResponseInvoiceP2PPostman::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::mid::GenerateResponseInvoiceP2PPostman& from_msg)
      : uuid_(arena, from.uuid_),
        card_(arena, from.card_),
        cardholdername_(arena, from.cardholdername_),
        bankname_(arena, from.bankname_),
        _cached_size_{0} {}

GenerateResponseInvoiceP2PPostman::GenerateResponseInvoiceP2PPostman(
    ::google::protobuf::Arena* arena,
    const GenerateResponseInvoiceP2PPostman& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GenerateResponseInvoiceP2PPostman* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.sum_ = from._impl_.sum_;

  // @@protoc_insertion_point(copy_constructor:mid.GenerateResponseInvoiceP2PPostman)
}
inline PROTOBUF_NDEBUG_INLINE GenerateResponseInvoiceP2PPostman::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : uuid_(arena),
        card_(arena),
        cardholdername_(arena),
        bankname_(arena),
        _cached_size_{0} {}

inline void GenerateResponseInvoiceP2PPostman::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sum_ = {};
}
GenerateResponseInvoiceP2PPostman::~GenerateResponseInvoiceP2PPostman() {
  // @@protoc_insertion_point(destructor:mid.GenerateResponseInvoiceP2PPostman)
  SharedDtor(*this);
}
inline void GenerateResponseInvoiceP2PPostman::SharedDtor(MessageLite& self) {
  GenerateResponseInvoiceP2PPostman& this_ = static_cast<GenerateResponseInvoiceP2PPostman&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.uuid_.Destroy();
  this_._impl_.card_.Destroy();
  this_._impl_.cardholdername_.Destroy();
  this_._impl_.bankname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GenerateResponseInvoiceP2PPostman::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GenerateResponseInvoiceP2PPostman(arena);
}
constexpr auto GenerateResponseInvoiceP2PPostman::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GenerateResponseInvoiceP2PPostman),
                                            alignof(GenerateResponseInvoiceP2PPostman));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GenerateResponseInvoiceP2PPostman::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GenerateResponseInvoiceP2PPostman_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GenerateResponseInvoiceP2PPostman::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GenerateResponseInvoiceP2PPostman>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GenerateResponseInvoiceP2PPostman::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GenerateResponseInvoiceP2PPostman>(), &GenerateResponseInvoiceP2PPostman::ByteSizeLong,
            &GenerateResponseInvoiceP2PPostman::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GenerateResponseInvoiceP2PPostman, _impl_._cached_size_),
        false,
    },
    &GenerateResponseInvoiceP2PPostman::kDescriptorMethods,
    &descriptor_table_serv_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GenerateResponseInvoiceP2PPostman::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 76, 2> GenerateResponseInvoiceP2PPostman::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mid::GenerateResponseInvoiceP2PPostman>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string Uuid = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateResponseInvoiceP2PPostman, _impl_.uuid_)}},
    // string Card = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateResponseInvoiceP2PPostman, _impl_.card_)}},
    // int32 Sum = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GenerateResponseInvoiceP2PPostman, _impl_.sum_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateResponseInvoiceP2PPostman, _impl_.sum_)}},
    // string CardHolderName = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateResponseInvoiceP2PPostman, _impl_.cardholdername_)}},
    // string BankName = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateResponseInvoiceP2PPostman, _impl_.bankname_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string Uuid = 1;
    {PROTOBUF_FIELD_OFFSET(GenerateResponseInvoiceP2PPostman, _impl_.uuid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string Card = 2;
    {PROTOBUF_FIELD_OFFSET(GenerateResponseInvoiceP2PPostman, _impl_.card_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 Sum = 3;
    {PROTOBUF_FIELD_OFFSET(GenerateResponseInvoiceP2PPostman, _impl_.sum_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string CardHolderName = 4;
    {PROTOBUF_FIELD_OFFSET(GenerateResponseInvoiceP2PPostman, _impl_.cardholdername_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string BankName = 5;
    {PROTOBUF_FIELD_OFFSET(GenerateResponseInvoiceP2PPostman, _impl_.bankname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\45\4\4\0\16\10\0\0"
    "mid.GenerateResponseInvoiceP2PPostman"
    "Uuid"
    "Card"
    "CardHolderName"
    "BankName"
  }},
};

PROTOBUF_NOINLINE void GenerateResponseInvoiceP2PPostman::Clear() {
// @@protoc_insertion_point(message_clear_start:mid.GenerateResponseInvoiceP2PPostman)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uuid_.ClearToEmpty();
  _impl_.card_.ClearToEmpty();
  _impl_.cardholdername_.ClearToEmpty();
  _impl_.bankname_.ClearToEmpty();
  _impl_.sum_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GenerateResponseInvoiceP2PPostman::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GenerateResponseInvoiceP2PPostman& this_ = static_cast<const GenerateResponseInvoiceP2PPostman&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GenerateResponseInvoiceP2PPostman::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GenerateResponseInvoiceP2PPostman& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:mid.GenerateResponseInvoiceP2PPostman)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string Uuid = 1;
          if (!this_._internal_uuid().empty()) {
            const std::string& _s = this_._internal_uuid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mid.GenerateResponseInvoiceP2PPostman.Uuid");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string Card = 2;
          if (!this_._internal_card().empty()) {
            const std::string& _s = this_._internal_card();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mid.GenerateResponseInvoiceP2PPostman.Card");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int32 Sum = 3;
          if (this_._internal_sum() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_sum(), target);
          }

          // string CardHolderName = 4;
          if (!this_._internal_cardholdername().empty()) {
            const std::string& _s = this_._internal_cardholdername();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mid.GenerateResponseInvoiceP2PPostman.CardHolderName");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // string BankName = 5;
          if (!this_._internal_bankname().empty()) {
            const std::string& _s = this_._internal_bankname();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mid.GenerateResponseInvoiceP2PPostman.BankName");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:mid.GenerateResponseInvoiceP2PPostman)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GenerateResponseInvoiceP2PPostman::ByteSizeLong(const MessageLite& base) {
          const GenerateResponseInvoiceP2PPostman& this_ = static_cast<const GenerateResponseInvoiceP2PPostman&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GenerateResponseInvoiceP2PPostman::ByteSizeLong() const {
          const GenerateResponseInvoiceP2PPostman& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:mid.GenerateResponseInvoiceP2PPostman)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string Uuid = 1;
            if (!this_._internal_uuid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_uuid());
            }
            // string Card = 2;
            if (!this_._internal_card().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_card());
            }
            // string CardHolderName = 4;
            if (!this_._internal_cardholdername().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_cardholdername());
            }
            // string BankName = 5;
            if (!this_._internal_bankname().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_bankname());
            }
            // int32 Sum = 3;
            if (this_._internal_sum() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_sum());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GenerateResponseInvoiceP2PPostman::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GenerateResponseInvoiceP2PPostman*>(&to_msg);
  auto& from = static_cast<const GenerateResponseInvoiceP2PPostman&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mid.GenerateResponseInvoiceP2PPostman)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_uuid().empty()) {
    _this->_internal_set_uuid(from._internal_uuid());
  }
  if (!from._internal_card().empty()) {
    _this->_internal_set_card(from._internal_card());
  }
  if (!from._internal_cardholdername().empty()) {
    _this->_internal_set_cardholdername(from._internal_cardholdername());
  }
  if (!from._internal_bankname().empty()) {
    _this->_internal_set_bankname(from._internal_bankname());
  }
  if (from._internal_sum() != 0) {
    _this->_impl_.sum_ = from._impl_.sum_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GenerateResponseInvoiceP2PPostman::CopyFrom(const GenerateResponseInvoiceP2PPostman& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mid.GenerateResponseInvoiceP2PPostman)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GenerateResponseInvoiceP2PPostman::InternalSwap(GenerateResponseInvoiceP2PPostman* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uuid_, &other->_impl_.uuid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.card_, &other->_impl_.card_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cardholdername_, &other->_impl_.cardholdername_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.bankname_, &other->_impl_.bankname_, arena);
        swap(_impl_.sum_, other->_impl_.sum_);
}

::google::protobuf::Metadata GenerateResponseInvoiceP2PPostman::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GenerateInvoiceRequestFPSPostman::_Internal {
 public:
};

GenerateInvoiceRequestFPSPostman::GenerateInvoiceRequestFPSPostman(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mid.GenerateInvoiceRequestFPSPostman)
}
GenerateInvoiceRequestFPSPostman::GenerateInvoiceRequestFPSPostman(
    ::google::protobuf::Arena* arena, const GenerateInvoiceRequestFPSPostman& from)
    : GenerateInvoiceRequestFPSPostman(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GenerateInvoiceRequestFPSPostman::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GenerateInvoiceRequestFPSPostman::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ordertype_),
           0,
           offsetof(Impl_, sum_) -
               offsetof(Impl_, ordertype_) +
               sizeof(Impl_::sum_));
}
GenerateInvoiceRequestFPSPostman::~GenerateInvoiceRequestFPSPostman() {
  // @@protoc_insertion_point(destructor:mid.GenerateInvoiceRequestFPSPostman)
  SharedDtor(*this);
}
inline void GenerateInvoiceRequestFPSPostman::SharedDtor(MessageLite& self) {
  GenerateInvoiceRequestFPSPostman& this_ = static_cast<GenerateInvoiceRequestFPSPostman&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* GenerateInvoiceRequestFPSPostman::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GenerateInvoiceRequestFPSPostman(arena);
}
constexpr auto GenerateInvoiceRequestFPSPostman::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GenerateInvoiceRequestFPSPostman),
                                            alignof(GenerateInvoiceRequestFPSPostman));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GenerateInvoiceRequestFPSPostman::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GenerateInvoiceRequestFPSPostman_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GenerateInvoiceRequestFPSPostman::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GenerateInvoiceRequestFPSPostman>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GenerateInvoiceRequestFPSPostman::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GenerateInvoiceRequestFPSPostman>(), &GenerateInvoiceRequestFPSPostman::ByteSizeLong,
            &GenerateInvoiceRequestFPSPostman::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GenerateInvoiceRequestFPSPostman, _impl_._cached_size_),
        false,
    },
    &GenerateInvoiceRequestFPSPostman::kDescriptorMethods,
    &descriptor_table_serv_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GenerateInvoiceRequestFPSPostman::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> GenerateInvoiceRequestFPSPostman::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mid::GenerateInvoiceRequestFPSPostman>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 Sum = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GenerateInvoiceRequestFPSPostman, _impl_.sum_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateInvoiceRequestFPSPostman, _impl_.sum_)}},
    // .mid.OrderType orderType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GenerateInvoiceRequestFPSPostman, _impl_.ordertype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateInvoiceRequestFPSPostman, _impl_.ordertype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .mid.OrderType orderType = 1;
    {PROTOBUF_FIELD_OFFSET(GenerateInvoiceRequestFPSPostman, _impl_.ordertype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 Sum = 2;
    {PROTOBUF_FIELD_OFFSET(GenerateInvoiceRequestFPSPostman, _impl_.sum_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GenerateInvoiceRequestFPSPostman::Clear() {
// @@protoc_insertion_point(message_clear_start:mid.GenerateInvoiceRequestFPSPostman)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.ordertype_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.sum_) -
      reinterpret_cast<char*>(&_impl_.ordertype_)) + sizeof(_impl_.sum_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GenerateInvoiceRequestFPSPostman::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GenerateInvoiceRequestFPSPostman& this_ = static_cast<const GenerateInvoiceRequestFPSPostman&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GenerateInvoiceRequestFPSPostman::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GenerateInvoiceRequestFPSPostman& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:mid.GenerateInvoiceRequestFPSPostman)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .mid.OrderType orderType = 1;
          if (this_._internal_ordertype() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_ordertype(), target);
          }

          // int32 Sum = 2;
          if (this_._internal_sum() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_sum(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:mid.GenerateInvoiceRequestFPSPostman)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GenerateInvoiceRequestFPSPostman::ByteSizeLong(const MessageLite& base) {
          const GenerateInvoiceRequestFPSPostman& this_ = static_cast<const GenerateInvoiceRequestFPSPostman&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GenerateInvoiceRequestFPSPostman::ByteSizeLong() const {
          const GenerateInvoiceRequestFPSPostman& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:mid.GenerateInvoiceRequestFPSPostman)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .mid.OrderType orderType = 1;
            if (this_._internal_ordertype() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_ordertype());
            }
            // int32 Sum = 2;
            if (this_._internal_sum() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_sum());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GenerateInvoiceRequestFPSPostman::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GenerateInvoiceRequestFPSPostman*>(&to_msg);
  auto& from = static_cast<const GenerateInvoiceRequestFPSPostman&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mid.GenerateInvoiceRequestFPSPostman)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ordertype() != 0) {
    _this->_impl_.ordertype_ = from._impl_.ordertype_;
  }
  if (from._internal_sum() != 0) {
    _this->_impl_.sum_ = from._impl_.sum_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GenerateInvoiceRequestFPSPostman::CopyFrom(const GenerateInvoiceRequestFPSPostman& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mid.GenerateInvoiceRequestFPSPostman)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GenerateInvoiceRequestFPSPostman::InternalSwap(GenerateInvoiceRequestFPSPostman* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GenerateInvoiceRequestFPSPostman, _impl_.sum_)
      + sizeof(GenerateInvoiceRequestFPSPostman::_impl_.sum_)
      - PROTOBUF_FIELD_OFFSET(GenerateInvoiceRequestFPSPostman, _impl_.ordertype_)>(
          reinterpret_cast<char*>(&_impl_.ordertype_),
          reinterpret_cast<char*>(&other->_impl_.ordertype_));
}

::google::protobuf::Metadata GenerateInvoiceRequestFPSPostman::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GenerateInvoiceResponseFPSPostman::_Internal {
 public:
};

GenerateInvoiceResponseFPSPostman::GenerateInvoiceResponseFPSPostman(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mid.GenerateInvoiceResponseFPSPostman)
}
inline PROTOBUF_NDEBUG_INLINE GenerateInvoiceResponseFPSPostman::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::mid::GenerateInvoiceResponseFPSPostman& from_msg)
      : uuid_(arena, from.uuid_),
        card_(arena, from.card_),
        cardholdername_(arena, from.cardholdername_),
        bankname_(arena, from.bankname_),
        _cached_size_{0} {}

GenerateInvoiceResponseFPSPostman::GenerateInvoiceResponseFPSPostman(
    ::google::protobuf::Arena* arena,
    const GenerateInvoiceResponseFPSPostman& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GenerateInvoiceResponseFPSPostman* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.sum_ = from._impl_.sum_;

  // @@protoc_insertion_point(copy_constructor:mid.GenerateInvoiceResponseFPSPostman)
}
inline PROTOBUF_NDEBUG_INLINE GenerateInvoiceResponseFPSPostman::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : uuid_(arena),
        card_(arena),
        cardholdername_(arena),
        bankname_(arena),
        _cached_size_{0} {}

inline void GenerateInvoiceResponseFPSPostman::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sum_ = {};
}
GenerateInvoiceResponseFPSPostman::~GenerateInvoiceResponseFPSPostman() {
  // @@protoc_insertion_point(destructor:mid.GenerateInvoiceResponseFPSPostman)
  SharedDtor(*this);
}
inline void GenerateInvoiceResponseFPSPostman::SharedDtor(MessageLite& self) {
  GenerateInvoiceResponseFPSPostman& this_ = static_cast<GenerateInvoiceResponseFPSPostman&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.uuid_.Destroy();
  this_._impl_.card_.Destroy();
  this_._impl_.cardholdername_.Destroy();
  this_._impl_.bankname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GenerateInvoiceResponseFPSPostman::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GenerateInvoiceResponseFPSPostman(arena);
}
constexpr auto GenerateInvoiceResponseFPSPostman::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GenerateInvoiceResponseFPSPostman),
                                            alignof(GenerateInvoiceResponseFPSPostman));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GenerateInvoiceResponseFPSPostman::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GenerateInvoiceResponseFPSPostman_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GenerateInvoiceResponseFPSPostman::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GenerateInvoiceResponseFPSPostman>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GenerateInvoiceResponseFPSPostman::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GenerateInvoiceResponseFPSPostman>(), &GenerateInvoiceResponseFPSPostman::ByteSizeLong,
            &GenerateInvoiceResponseFPSPostman::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GenerateInvoiceResponseFPSPostman, _impl_._cached_size_),
        false,
    },
    &GenerateInvoiceResponseFPSPostman::kDescriptorMethods,
    &descriptor_table_serv_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GenerateInvoiceResponseFPSPostman::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 76, 2> GenerateInvoiceResponseFPSPostman::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mid::GenerateInvoiceResponseFPSPostman>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string Uuid = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateInvoiceResponseFPSPostman, _impl_.uuid_)}},
    // string Card = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateInvoiceResponseFPSPostman, _impl_.card_)}},
    // int32 Sum = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GenerateInvoiceResponseFPSPostman, _impl_.sum_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateInvoiceResponseFPSPostman, _impl_.sum_)}},
    // string CardHolderName = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateInvoiceResponseFPSPostman, _impl_.cardholdername_)}},
    // string BankName = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateInvoiceResponseFPSPostman, _impl_.bankname_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string Uuid = 1;
    {PROTOBUF_FIELD_OFFSET(GenerateInvoiceResponseFPSPostman, _impl_.uuid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string Card = 2;
    {PROTOBUF_FIELD_OFFSET(GenerateInvoiceResponseFPSPostman, _impl_.card_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 Sum = 3;
    {PROTOBUF_FIELD_OFFSET(GenerateInvoiceResponseFPSPostman, _impl_.sum_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string CardHolderName = 4;
    {PROTOBUF_FIELD_OFFSET(GenerateInvoiceResponseFPSPostman, _impl_.cardholdername_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string BankName = 5;
    {PROTOBUF_FIELD_OFFSET(GenerateInvoiceResponseFPSPostman, _impl_.bankname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\45\4\4\0\16\10\0\0"
    "mid.GenerateInvoiceResponseFPSPostman"
    "Uuid"
    "Card"
    "CardHolderName"
    "BankName"
  }},
};

PROTOBUF_NOINLINE void GenerateInvoiceResponseFPSPostman::Clear() {
// @@protoc_insertion_point(message_clear_start:mid.GenerateInvoiceResponseFPSPostman)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uuid_.ClearToEmpty();
  _impl_.card_.ClearToEmpty();
  _impl_.cardholdername_.ClearToEmpty();
  _impl_.bankname_.ClearToEmpty();
  _impl_.sum_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GenerateInvoiceResponseFPSPostman::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GenerateInvoiceResponseFPSPostman& this_ = static_cast<const GenerateInvoiceResponseFPSPostman&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GenerateInvoiceResponseFPSPostman::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GenerateInvoiceResponseFPSPostman& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:mid.GenerateInvoiceResponseFPSPostman)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string Uuid = 1;
          if (!this_._internal_uuid().empty()) {
            const std::string& _s = this_._internal_uuid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mid.GenerateInvoiceResponseFPSPostman.Uuid");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string Card = 2;
          if (!this_._internal_card().empty()) {
            const std::string& _s = this_._internal_card();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mid.GenerateInvoiceResponseFPSPostman.Card");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int32 Sum = 3;
          if (this_._internal_sum() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_sum(), target);
          }

          // string CardHolderName = 4;
          if (!this_._internal_cardholdername().empty()) {
            const std::string& _s = this_._internal_cardholdername();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mid.GenerateInvoiceResponseFPSPostman.CardHolderName");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // string BankName = 5;
          if (!this_._internal_bankname().empty()) {
            const std::string& _s = this_._internal_bankname();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mid.GenerateInvoiceResponseFPSPostman.BankName");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:mid.GenerateInvoiceResponseFPSPostman)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GenerateInvoiceResponseFPSPostman::ByteSizeLong(const MessageLite& base) {
          const GenerateInvoiceResponseFPSPostman& this_ = static_cast<const GenerateInvoiceResponseFPSPostman&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GenerateInvoiceResponseFPSPostman::ByteSizeLong() const {
          const GenerateInvoiceResponseFPSPostman& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:mid.GenerateInvoiceResponseFPSPostman)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string Uuid = 1;
            if (!this_._internal_uuid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_uuid());
            }
            // string Card = 2;
            if (!this_._internal_card().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_card());
            }
            // string CardHolderName = 4;
            if (!this_._internal_cardholdername().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_cardholdername());
            }
            // string BankName = 5;
            if (!this_._internal_bankname().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_bankname());
            }
            // int32 Sum = 3;
            if (this_._internal_sum() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_sum());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GenerateInvoiceResponseFPSPostman::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GenerateInvoiceResponseFPSPostman*>(&to_msg);
  auto& from = static_cast<const GenerateInvoiceResponseFPSPostman&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mid.GenerateInvoiceResponseFPSPostman)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_uuid().empty()) {
    _this->_internal_set_uuid(from._internal_uuid());
  }
  if (!from._internal_card().empty()) {
    _this->_internal_set_card(from._internal_card());
  }
  if (!from._internal_cardholdername().empty()) {
    _this->_internal_set_cardholdername(from._internal_cardholdername());
  }
  if (!from._internal_bankname().empty()) {
    _this->_internal_set_bankname(from._internal_bankname());
  }
  if (from._internal_sum() != 0) {
    _this->_impl_.sum_ = from._impl_.sum_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GenerateInvoiceResponseFPSPostman::CopyFrom(const GenerateInvoiceResponseFPSPostman& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mid.GenerateInvoiceResponseFPSPostman)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GenerateInvoiceResponseFPSPostman::InternalSwap(GenerateInvoiceResponseFPSPostman* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uuid_, &other->_impl_.uuid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.card_, &other->_impl_.card_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cardholdername_, &other->_impl_.cardholdername_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.bankname_, &other->_impl_.bankname_, arena);
        swap(_impl_.sum_, other->_impl_.sum_);
}

::google::protobuf::Metadata GenerateInvoiceResponseFPSPostman::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GenerateRequestPayoutPostman::_Internal {
 public:
};

GenerateRequestPayoutPostman::GenerateRequestPayoutPostman(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mid.GenerateRequestPayoutPostman)
}
inline PROTOBUF_NDEBUG_INLINE GenerateRequestPayoutPostman::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::mid::GenerateRequestPayoutPostman& from_msg)
      : card_(arena, from.card_),
        _cached_size_{0} {}

GenerateRequestPayoutPostman::GenerateRequestPayoutPostman(
    ::google::protobuf::Arena* arena,
    const GenerateRequestPayoutPostman& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GenerateRequestPayoutPostman* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ordertype_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, ordertype_),
           offsetof(Impl_, sum_) -
               offsetof(Impl_, ordertype_) +
               sizeof(Impl_::sum_));

  // @@protoc_insertion_point(copy_constructor:mid.GenerateRequestPayoutPostman)
}
inline PROTOBUF_NDEBUG_INLINE GenerateRequestPayoutPostman::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : card_(arena),
        _cached_size_{0} {}

inline void GenerateRequestPayoutPostman::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ordertype_),
           0,
           offsetof(Impl_, sum_) -
               offsetof(Impl_, ordertype_) +
               sizeof(Impl_::sum_));
}
GenerateRequestPayoutPostman::~GenerateRequestPayoutPostman() {
  // @@protoc_insertion_point(destructor:mid.GenerateRequestPayoutPostman)
  SharedDtor(*this);
}
inline void GenerateRequestPayoutPostman::SharedDtor(MessageLite& self) {
  GenerateRequestPayoutPostman& this_ = static_cast<GenerateRequestPayoutPostman&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.card_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GenerateRequestPayoutPostman::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GenerateRequestPayoutPostman(arena);
}
constexpr auto GenerateRequestPayoutPostman::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GenerateRequestPayoutPostman),
                                            alignof(GenerateRequestPayoutPostman));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GenerateRequestPayoutPostman::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GenerateRequestPayoutPostman_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GenerateRequestPayoutPostman::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GenerateRequestPayoutPostman>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GenerateRequestPayoutPostman::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GenerateRequestPayoutPostman>(), &GenerateRequestPayoutPostman::ByteSizeLong,
            &GenerateRequestPayoutPostman::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GenerateRequestPayoutPostman, _impl_._cached_size_),
        false,
    },
    &GenerateRequestPayoutPostman::kDescriptorMethods,
    &descriptor_table_serv_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GenerateRequestPayoutPostman::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 45, 2> GenerateRequestPayoutPostman::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mid::GenerateRequestPayoutPostman>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .mid.OrderType orderType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GenerateRequestPayoutPostman, _impl_.ordertype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateRequestPayoutPostman, _impl_.ordertype_)}},
    // int32 sum = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GenerateRequestPayoutPostman, _impl_.sum_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateRequestPayoutPostman, _impl_.sum_)}},
    // string card = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateRequestPayoutPostman, _impl_.card_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .mid.OrderType orderType = 1;
    {PROTOBUF_FIELD_OFFSET(GenerateRequestPayoutPostman, _impl_.ordertype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 sum = 2;
    {PROTOBUF_FIELD_OFFSET(GenerateRequestPayoutPostman, _impl_.sum_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string card = 3;
    {PROTOBUF_FIELD_OFFSET(GenerateRequestPayoutPostman, _impl_.card_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\40\0\0\4\0\0\0\0"
    "mid.GenerateRequestPayoutPostman"
    "card"
  }},
};

PROTOBUF_NOINLINE void GenerateRequestPayoutPostman::Clear() {
// @@protoc_insertion_point(message_clear_start:mid.GenerateRequestPayoutPostman)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.card_.ClearToEmpty();
  ::memset(&_impl_.ordertype_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.sum_) -
      reinterpret_cast<char*>(&_impl_.ordertype_)) + sizeof(_impl_.sum_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GenerateRequestPayoutPostman::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GenerateRequestPayoutPostman& this_ = static_cast<const GenerateRequestPayoutPostman&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GenerateRequestPayoutPostman::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GenerateRequestPayoutPostman& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:mid.GenerateRequestPayoutPostman)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .mid.OrderType orderType = 1;
          if (this_._internal_ordertype() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_ordertype(), target);
          }

          // int32 sum = 2;
          if (this_._internal_sum() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_sum(), target);
          }

          // string card = 3;
          if (!this_._internal_card().empty()) {
            const std::string& _s = this_._internal_card();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mid.GenerateRequestPayoutPostman.card");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:mid.GenerateRequestPayoutPostman)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GenerateRequestPayoutPostman::ByteSizeLong(const MessageLite& base) {
          const GenerateRequestPayoutPostman& this_ = static_cast<const GenerateRequestPayoutPostman&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GenerateRequestPayoutPostman::ByteSizeLong() const {
          const GenerateRequestPayoutPostman& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:mid.GenerateRequestPayoutPostman)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string card = 3;
            if (!this_._internal_card().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_card());
            }
            // .mid.OrderType orderType = 1;
            if (this_._internal_ordertype() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_ordertype());
            }
            // int32 sum = 2;
            if (this_._internal_sum() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_sum());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GenerateRequestPayoutPostman::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GenerateRequestPayoutPostman*>(&to_msg);
  auto& from = static_cast<const GenerateRequestPayoutPostman&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mid.GenerateRequestPayoutPostman)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_card().empty()) {
    _this->_internal_set_card(from._internal_card());
  }
  if (from._internal_ordertype() != 0) {
    _this->_impl_.ordertype_ = from._impl_.ordertype_;
  }
  if (from._internal_sum() != 0) {
    _this->_impl_.sum_ = from._impl_.sum_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GenerateRequestPayoutPostman::CopyFrom(const GenerateRequestPayoutPostman& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mid.GenerateRequestPayoutPostman)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GenerateRequestPayoutPostman::InternalSwap(GenerateRequestPayoutPostman* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.card_, &other->_impl_.card_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GenerateRequestPayoutPostman, _impl_.sum_)
      + sizeof(GenerateRequestPayoutPostman::_impl_.sum_)
      - PROTOBUF_FIELD_OFFSET(GenerateRequestPayoutPostman, _impl_.ordertype_)>(
          reinterpret_cast<char*>(&_impl_.ordertype_),
          reinterpret_cast<char*>(&other->_impl_.ordertype_));
}

::google::protobuf::Metadata GenerateRequestPayoutPostman::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GenerateResponsePayoutPostman::_Internal {
 public:
};

GenerateResponsePayoutPostman::GenerateResponsePayoutPostman(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:mid.GenerateResponsePayoutPostman)
}
inline PROTOBUF_NDEBUG_INLINE GenerateResponsePayoutPostman::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::mid::GenerateResponsePayoutPostman& from_msg)
      : uuid_(arena, from.uuid_),
        _cached_size_{0} {}

GenerateResponsePayoutPostman::GenerateResponsePayoutPostman(
    ::google::protobuf::Arena* arena,
    const GenerateResponsePayoutPostman& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GenerateResponsePayoutPostman* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, success_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::success_));

  // @@protoc_insertion_point(copy_constructor:mid.GenerateResponsePayoutPostman)
}
inline PROTOBUF_NDEBUG_INLINE GenerateResponsePayoutPostman::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : uuid_(arena),
        _cached_size_{0} {}

inline void GenerateResponsePayoutPostman::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, success_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::success_));
}
GenerateResponsePayoutPostman::~GenerateResponsePayoutPostman() {
  // @@protoc_insertion_point(destructor:mid.GenerateResponsePayoutPostman)
  SharedDtor(*this);
}
inline void GenerateResponsePayoutPostman::SharedDtor(MessageLite& self) {
  GenerateResponsePayoutPostman& this_ = static_cast<GenerateResponsePayoutPostman&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.uuid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GenerateResponsePayoutPostman::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GenerateResponsePayoutPostman(arena);
}
constexpr auto GenerateResponsePayoutPostman::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GenerateResponsePayoutPostman),
                                            alignof(GenerateResponsePayoutPostman));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GenerateResponsePayoutPostman::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GenerateResponsePayoutPostman_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GenerateResponsePayoutPostman::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GenerateResponsePayoutPostman>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GenerateResponsePayoutPostman::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GenerateResponsePayoutPostman>(), &GenerateResponsePayoutPostman::ByteSizeLong,
            &GenerateResponsePayoutPostman::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GenerateResponsePayoutPostman, _impl_._cached_size_),
        false,
    },
    &GenerateResponsePayoutPostman::kDescriptorMethods,
    &descriptor_table_serv_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GenerateResponsePayoutPostman::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 46, 2> GenerateResponsePayoutPostman::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::mid::GenerateResponsePayoutPostman>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GenerateResponsePayoutPostman, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateResponsePayoutPostman, _impl_.id_)}},
    // string uuid = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateResponsePayoutPostman, _impl_.uuid_)}},
    // bool success = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(GenerateResponsePayoutPostman, _impl_.success_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(GenerateResponsePayoutPostman, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(GenerateResponsePayoutPostman, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string uuid = 2;
    {PROTOBUF_FIELD_OFFSET(GenerateResponsePayoutPostman, _impl_.uuid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool success = 3;
    {PROTOBUF_FIELD_OFFSET(GenerateResponsePayoutPostman, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\41\0\4\0\0\0\0\0"
    "mid.GenerateResponsePayoutPostman"
    "uuid"
  }},
};

PROTOBUF_NOINLINE void GenerateResponsePayoutPostman::Clear() {
// @@protoc_insertion_point(message_clear_start:mid.GenerateResponsePayoutPostman)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uuid_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.success_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.success_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GenerateResponsePayoutPostman::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GenerateResponsePayoutPostman& this_ = static_cast<const GenerateResponsePayoutPostman&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GenerateResponsePayoutPostman::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GenerateResponsePayoutPostman& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:mid.GenerateResponsePayoutPostman)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 id = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          // string uuid = 2;
          if (!this_._internal_uuid().empty()) {
            const std::string& _s = this_._internal_uuid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "mid.GenerateResponsePayoutPostman.uuid");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // bool success = 3;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_success(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:mid.GenerateResponsePayoutPostman)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GenerateResponsePayoutPostman::ByteSizeLong(const MessageLite& base) {
          const GenerateResponsePayoutPostman& this_ = static_cast<const GenerateResponsePayoutPostman&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GenerateResponsePayoutPostman::ByteSizeLong() const {
          const GenerateResponsePayoutPostman& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:mid.GenerateResponsePayoutPostman)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string uuid = 2;
            if (!this_._internal_uuid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_uuid());
            }
            // int32 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
            // bool success = 3;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GenerateResponsePayoutPostman::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GenerateResponsePayoutPostman*>(&to_msg);
  auto& from = static_cast<const GenerateResponsePayoutPostman&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mid.GenerateResponsePayoutPostman)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_uuid().empty()) {
    _this->_internal_set_uuid(from._internal_uuid());
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GenerateResponsePayoutPostman::CopyFrom(const GenerateResponsePayoutPostman& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mid.GenerateResponsePayoutPostman)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GenerateResponsePayoutPostman::InternalSwap(GenerateResponsePayoutPostman* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uuid_, &other->_impl_.uuid_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GenerateResponsePayoutPostman, _impl_.success_)
      + sizeof(GenerateResponsePayoutPostman::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(GenerateResponsePayoutPostman, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata GenerateResponsePayoutPostman::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace mid
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_serv_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
