// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serv.proto
// Protobuf C++ Version: 5.29.0

#ifndef serv_2eproto_2epb_2eh
#define serv_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_serv_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_serv_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_serv_2eproto;
namespace mid {
class GenerateInvoiceRequestFPSPostman;
struct GenerateInvoiceRequestFPSPostmanDefaultTypeInternal;
extern GenerateInvoiceRequestFPSPostmanDefaultTypeInternal _GenerateInvoiceRequestFPSPostman_default_instance_;
class GenerateInvoiceResponseFPSPostman;
struct GenerateInvoiceResponseFPSPostmanDefaultTypeInternal;
extern GenerateInvoiceResponseFPSPostmanDefaultTypeInternal _GenerateInvoiceResponseFPSPostman_default_instance_;
class GenerateRequestP2PPostman;
struct GenerateRequestP2PPostmanDefaultTypeInternal;
extern GenerateRequestP2PPostmanDefaultTypeInternal _GenerateRequestP2PPostman_default_instance_;
class GenerateRequestPayoutPostman;
struct GenerateRequestPayoutPostmanDefaultTypeInternal;
extern GenerateRequestPayoutPostmanDefaultTypeInternal _GenerateRequestPayoutPostman_default_instance_;
class GenerateResponseInvoiceP2PPostman;
struct GenerateResponseInvoiceP2PPostmanDefaultTypeInternal;
extern GenerateResponseInvoiceP2PPostmanDefaultTypeInternal _GenerateResponseInvoiceP2PPostman_default_instance_;
class GenerateResponsePayoutPostman;
struct GenerateResponsePayoutPostmanDefaultTypeInternal;
extern GenerateResponsePayoutPostmanDefaultTypeInternal _GenerateResponsePayoutPostman_default_instance_;
}  // namespace mid
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace mid {
enum OrderType : int {
  UNKNOWN = 0,
  P2P = 1,
  FPS = 2,
  OrderType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  OrderType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool OrderType_IsValid(int value);
extern const uint32_t OrderType_internal_data_[];
constexpr OrderType OrderType_MIN = static_cast<OrderType>(0);
constexpr OrderType OrderType_MAX = static_cast<OrderType>(2);
constexpr int OrderType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
OrderType_descriptor();
template <typename T>
const std::string& OrderType_Name(T value) {
  static_assert(std::is_same<T, OrderType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to OrderType_Name().");
  return OrderType_Name(static_cast<OrderType>(value));
}
template <>
inline const std::string& OrderType_Name(OrderType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<OrderType_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool OrderType_Parse(absl::string_view name, OrderType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OrderType>(
      OrderType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class GenerateResponsePayoutPostman final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mid.GenerateResponsePayoutPostman) */ {
 public:
  inline GenerateResponsePayoutPostman() : GenerateResponsePayoutPostman(nullptr) {}
  ~GenerateResponsePayoutPostman() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GenerateResponsePayoutPostman* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GenerateResponsePayoutPostman));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GenerateResponsePayoutPostman(
      ::google::protobuf::internal::ConstantInitialized);

  inline GenerateResponsePayoutPostman(const GenerateResponsePayoutPostman& from) : GenerateResponsePayoutPostman(nullptr, from) {}
  inline GenerateResponsePayoutPostman(GenerateResponsePayoutPostman&& from) noexcept
      : GenerateResponsePayoutPostman(nullptr, std::move(from)) {}
  inline GenerateResponsePayoutPostman& operator=(const GenerateResponsePayoutPostman& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenerateResponsePayoutPostman& operator=(GenerateResponsePayoutPostman&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GenerateResponsePayoutPostman& default_instance() {
    return *internal_default_instance();
  }
  static inline const GenerateResponsePayoutPostman* internal_default_instance() {
    return reinterpret_cast<const GenerateResponsePayoutPostman*>(
        &_GenerateResponsePayoutPostman_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(GenerateResponsePayoutPostman& a, GenerateResponsePayoutPostman& b) { a.Swap(&b); }
  inline void Swap(GenerateResponsePayoutPostman* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GenerateResponsePayoutPostman* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GenerateResponsePayoutPostman* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GenerateResponsePayoutPostman>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GenerateResponsePayoutPostman& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GenerateResponsePayoutPostman& from) { GenerateResponsePayoutPostman::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GenerateResponsePayoutPostman* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mid.GenerateResponsePayoutPostman"; }

 protected:
  explicit GenerateResponsePayoutPostman(::google::protobuf::Arena* arena);
  GenerateResponsePayoutPostman(::google::protobuf::Arena* arena, const GenerateResponsePayoutPostman& from);
  GenerateResponsePayoutPostman(::google::protobuf::Arena* arena, GenerateResponsePayoutPostman&& from) noexcept
      : GenerateResponsePayoutPostman(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUuidFieldNumber = 2,
    kIdFieldNumber = 1,
    kSuccessFieldNumber = 3,
  };
  // string uuid = 2;
  void clear_uuid() ;
  const std::string& uuid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* value);

  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(
      const std::string& value);
  std::string* _internal_mutable_uuid();

  public:
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // bool success = 3;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:mid.GenerateResponsePayoutPostman)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      46, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GenerateResponsePayoutPostman& from_msg);
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    ::int32_t id_;
    bool success_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serv_2eproto;
};
// -------------------------------------------------------------------

class GenerateResponseInvoiceP2PPostman final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mid.GenerateResponseInvoiceP2PPostman) */ {
 public:
  inline GenerateResponseInvoiceP2PPostman() : GenerateResponseInvoiceP2PPostman(nullptr) {}
  ~GenerateResponseInvoiceP2PPostman() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GenerateResponseInvoiceP2PPostman* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GenerateResponseInvoiceP2PPostman));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GenerateResponseInvoiceP2PPostman(
      ::google::protobuf::internal::ConstantInitialized);

  inline GenerateResponseInvoiceP2PPostman(const GenerateResponseInvoiceP2PPostman& from) : GenerateResponseInvoiceP2PPostman(nullptr, from) {}
  inline GenerateResponseInvoiceP2PPostman(GenerateResponseInvoiceP2PPostman&& from) noexcept
      : GenerateResponseInvoiceP2PPostman(nullptr, std::move(from)) {}
  inline GenerateResponseInvoiceP2PPostman& operator=(const GenerateResponseInvoiceP2PPostman& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenerateResponseInvoiceP2PPostman& operator=(GenerateResponseInvoiceP2PPostman&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GenerateResponseInvoiceP2PPostman& default_instance() {
    return *internal_default_instance();
  }
  static inline const GenerateResponseInvoiceP2PPostman* internal_default_instance() {
    return reinterpret_cast<const GenerateResponseInvoiceP2PPostman*>(
        &_GenerateResponseInvoiceP2PPostman_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(GenerateResponseInvoiceP2PPostman& a, GenerateResponseInvoiceP2PPostman& b) { a.Swap(&b); }
  inline void Swap(GenerateResponseInvoiceP2PPostman* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GenerateResponseInvoiceP2PPostman* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GenerateResponseInvoiceP2PPostman* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GenerateResponseInvoiceP2PPostman>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GenerateResponseInvoiceP2PPostman& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GenerateResponseInvoiceP2PPostman& from) { GenerateResponseInvoiceP2PPostman::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GenerateResponseInvoiceP2PPostman* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mid.GenerateResponseInvoiceP2PPostman"; }

 protected:
  explicit GenerateResponseInvoiceP2PPostman(::google::protobuf::Arena* arena);
  GenerateResponseInvoiceP2PPostman(::google::protobuf::Arena* arena, const GenerateResponseInvoiceP2PPostman& from);
  GenerateResponseInvoiceP2PPostman(::google::protobuf::Arena* arena, GenerateResponseInvoiceP2PPostman&& from) noexcept
      : GenerateResponseInvoiceP2PPostman(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUuidFieldNumber = 1,
    kCardFieldNumber = 2,
    kCardHolderNameFieldNumber = 4,
    kBankNameFieldNumber = 5,
    kSumFieldNumber = 3,
  };
  // string Uuid = 1;
  void clear_uuid() ;
  const std::string& uuid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* value);

  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(
      const std::string& value);
  std::string* _internal_mutable_uuid();

  public:
  // string Card = 2;
  void clear_card() ;
  const std::string& card() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_card(Arg_&& arg, Args_... args);
  std::string* mutable_card();
  PROTOBUF_NODISCARD std::string* release_card();
  void set_allocated_card(std::string* value);

  private:
  const std::string& _internal_card() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_card(
      const std::string& value);
  std::string* _internal_mutable_card();

  public:
  // string CardHolderName = 4;
  void clear_cardholdername() ;
  const std::string& cardholdername() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cardholdername(Arg_&& arg, Args_... args);
  std::string* mutable_cardholdername();
  PROTOBUF_NODISCARD std::string* release_cardholdername();
  void set_allocated_cardholdername(std::string* value);

  private:
  const std::string& _internal_cardholdername() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cardholdername(
      const std::string& value);
  std::string* _internal_mutable_cardholdername();

  public:
  // string BankName = 5;
  void clear_bankname() ;
  const std::string& bankname() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_bankname(Arg_&& arg, Args_... args);
  std::string* mutable_bankname();
  PROTOBUF_NODISCARD std::string* release_bankname();
  void set_allocated_bankname(std::string* value);

  private:
  const std::string& _internal_bankname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bankname(
      const std::string& value);
  std::string* _internal_mutable_bankname();

  public:
  // int32 Sum = 3;
  void clear_sum() ;
  ::int32_t sum() const;
  void set_sum(::int32_t value);

  private:
  ::int32_t _internal_sum() const;
  void _internal_set_sum(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mid.GenerateResponseInvoiceP2PPostman)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      76, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GenerateResponseInvoiceP2PPostman& from_msg);
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    ::google::protobuf::internal::ArenaStringPtr card_;
    ::google::protobuf::internal::ArenaStringPtr cardholdername_;
    ::google::protobuf::internal::ArenaStringPtr bankname_;
    ::int32_t sum_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serv_2eproto;
};
// -------------------------------------------------------------------

class GenerateRequestPayoutPostman final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mid.GenerateRequestPayoutPostman) */ {
 public:
  inline GenerateRequestPayoutPostman() : GenerateRequestPayoutPostman(nullptr) {}
  ~GenerateRequestPayoutPostman() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GenerateRequestPayoutPostman* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GenerateRequestPayoutPostman));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GenerateRequestPayoutPostman(
      ::google::protobuf::internal::ConstantInitialized);

  inline GenerateRequestPayoutPostman(const GenerateRequestPayoutPostman& from) : GenerateRequestPayoutPostman(nullptr, from) {}
  inline GenerateRequestPayoutPostman(GenerateRequestPayoutPostman&& from) noexcept
      : GenerateRequestPayoutPostman(nullptr, std::move(from)) {}
  inline GenerateRequestPayoutPostman& operator=(const GenerateRequestPayoutPostman& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenerateRequestPayoutPostman& operator=(GenerateRequestPayoutPostman&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GenerateRequestPayoutPostman& default_instance() {
    return *internal_default_instance();
  }
  static inline const GenerateRequestPayoutPostman* internal_default_instance() {
    return reinterpret_cast<const GenerateRequestPayoutPostman*>(
        &_GenerateRequestPayoutPostman_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(GenerateRequestPayoutPostman& a, GenerateRequestPayoutPostman& b) { a.Swap(&b); }
  inline void Swap(GenerateRequestPayoutPostman* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GenerateRequestPayoutPostman* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GenerateRequestPayoutPostman* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GenerateRequestPayoutPostman>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GenerateRequestPayoutPostman& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GenerateRequestPayoutPostman& from) { GenerateRequestPayoutPostman::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GenerateRequestPayoutPostman* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mid.GenerateRequestPayoutPostman"; }

 protected:
  explicit GenerateRequestPayoutPostman(::google::protobuf::Arena* arena);
  GenerateRequestPayoutPostman(::google::protobuf::Arena* arena, const GenerateRequestPayoutPostman& from);
  GenerateRequestPayoutPostman(::google::protobuf::Arena* arena, GenerateRequestPayoutPostman&& from) noexcept
      : GenerateRequestPayoutPostman(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCardFieldNumber = 3,
    kOrderTypeFieldNumber = 1,
    kSumFieldNumber = 2,
  };
  // string card = 3;
  void clear_card() ;
  const std::string& card() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_card(Arg_&& arg, Args_... args);
  std::string* mutable_card();
  PROTOBUF_NODISCARD std::string* release_card();
  void set_allocated_card(std::string* value);

  private:
  const std::string& _internal_card() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_card(
      const std::string& value);
  std::string* _internal_mutable_card();

  public:
  // .mid.OrderType orderType = 1;
  void clear_ordertype() ;
  ::mid::OrderType ordertype() const;
  void set_ordertype(::mid::OrderType value);

  private:
  ::mid::OrderType _internal_ordertype() const;
  void _internal_set_ordertype(::mid::OrderType value);

  public:
  // int32 sum = 2;
  void clear_sum() ;
  ::int32_t sum() const;
  void set_sum(::int32_t value);

  private:
  ::int32_t _internal_sum() const;
  void _internal_set_sum(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mid.GenerateRequestPayoutPostman)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      45, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GenerateRequestPayoutPostman& from_msg);
    ::google::protobuf::internal::ArenaStringPtr card_;
    int ordertype_;
    ::int32_t sum_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serv_2eproto;
};
// -------------------------------------------------------------------

class GenerateRequestP2PPostman final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mid.GenerateRequestP2PPostman) */ {
 public:
  inline GenerateRequestP2PPostman() : GenerateRequestP2PPostman(nullptr) {}
  ~GenerateRequestP2PPostman() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GenerateRequestP2PPostman* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GenerateRequestP2PPostman));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GenerateRequestP2PPostman(
      ::google::protobuf::internal::ConstantInitialized);

  inline GenerateRequestP2PPostman(const GenerateRequestP2PPostman& from) : GenerateRequestP2PPostman(nullptr, from) {}
  inline GenerateRequestP2PPostman(GenerateRequestP2PPostman&& from) noexcept
      : GenerateRequestP2PPostman(nullptr, std::move(from)) {}
  inline GenerateRequestP2PPostman& operator=(const GenerateRequestP2PPostman& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenerateRequestP2PPostman& operator=(GenerateRequestP2PPostman&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GenerateRequestP2PPostman& default_instance() {
    return *internal_default_instance();
  }
  static inline const GenerateRequestP2PPostman* internal_default_instance() {
    return reinterpret_cast<const GenerateRequestP2PPostman*>(
        &_GenerateRequestP2PPostman_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GenerateRequestP2PPostman& a, GenerateRequestP2PPostman& b) { a.Swap(&b); }
  inline void Swap(GenerateRequestP2PPostman* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GenerateRequestP2PPostman* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GenerateRequestP2PPostman* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GenerateRequestP2PPostman>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GenerateRequestP2PPostman& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GenerateRequestP2PPostman& from) { GenerateRequestP2PPostman::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GenerateRequestP2PPostman* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mid.GenerateRequestP2PPostman"; }

 protected:
  explicit GenerateRequestP2PPostman(::google::protobuf::Arena* arena);
  GenerateRequestP2PPostman(::google::protobuf::Arena* arena, const GenerateRequestP2PPostman& from);
  GenerateRequestP2PPostman(::google::protobuf::Arena* arena, GenerateRequestP2PPostman&& from) noexcept
      : GenerateRequestP2PPostman(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOrderTypeFieldNumber = 1,
    kSumFieldNumber = 2,
  };
  // .mid.OrderType orderType = 1;
  void clear_ordertype() ;
  ::mid::OrderType ordertype() const;
  void set_ordertype(::mid::OrderType value);

  private:
  ::mid::OrderType _internal_ordertype() const;
  void _internal_set_ordertype(::mid::OrderType value);

  public:
  // int32 Sum = 2;
  void clear_sum() ;
  ::int32_t sum() const;
  void set_sum(::int32_t value);

  private:
  ::int32_t _internal_sum() const;
  void _internal_set_sum(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mid.GenerateRequestP2PPostman)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GenerateRequestP2PPostman& from_msg);
    int ordertype_;
    ::int32_t sum_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serv_2eproto;
};
// -------------------------------------------------------------------

class GenerateInvoiceResponseFPSPostman final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mid.GenerateInvoiceResponseFPSPostman) */ {
 public:
  inline GenerateInvoiceResponseFPSPostman() : GenerateInvoiceResponseFPSPostman(nullptr) {}
  ~GenerateInvoiceResponseFPSPostman() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GenerateInvoiceResponseFPSPostman* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GenerateInvoiceResponseFPSPostman));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GenerateInvoiceResponseFPSPostman(
      ::google::protobuf::internal::ConstantInitialized);

  inline GenerateInvoiceResponseFPSPostman(const GenerateInvoiceResponseFPSPostman& from) : GenerateInvoiceResponseFPSPostman(nullptr, from) {}
  inline GenerateInvoiceResponseFPSPostman(GenerateInvoiceResponseFPSPostman&& from) noexcept
      : GenerateInvoiceResponseFPSPostman(nullptr, std::move(from)) {}
  inline GenerateInvoiceResponseFPSPostman& operator=(const GenerateInvoiceResponseFPSPostman& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenerateInvoiceResponseFPSPostman& operator=(GenerateInvoiceResponseFPSPostman&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GenerateInvoiceResponseFPSPostman& default_instance() {
    return *internal_default_instance();
  }
  static inline const GenerateInvoiceResponseFPSPostman* internal_default_instance() {
    return reinterpret_cast<const GenerateInvoiceResponseFPSPostman*>(
        &_GenerateInvoiceResponseFPSPostman_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(GenerateInvoiceResponseFPSPostman& a, GenerateInvoiceResponseFPSPostman& b) { a.Swap(&b); }
  inline void Swap(GenerateInvoiceResponseFPSPostman* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GenerateInvoiceResponseFPSPostman* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GenerateInvoiceResponseFPSPostman* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GenerateInvoiceResponseFPSPostman>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GenerateInvoiceResponseFPSPostman& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GenerateInvoiceResponseFPSPostman& from) { GenerateInvoiceResponseFPSPostman::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GenerateInvoiceResponseFPSPostman* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mid.GenerateInvoiceResponseFPSPostman"; }

 protected:
  explicit GenerateInvoiceResponseFPSPostman(::google::protobuf::Arena* arena);
  GenerateInvoiceResponseFPSPostman(::google::protobuf::Arena* arena, const GenerateInvoiceResponseFPSPostman& from);
  GenerateInvoiceResponseFPSPostman(::google::protobuf::Arena* arena, GenerateInvoiceResponseFPSPostman&& from) noexcept
      : GenerateInvoiceResponseFPSPostman(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUuidFieldNumber = 1,
    kCardFieldNumber = 2,
    kCardHolderNameFieldNumber = 4,
    kBankNameFieldNumber = 5,
    kSumFieldNumber = 3,
  };
  // string Uuid = 1;
  void clear_uuid() ;
  const std::string& uuid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* value);

  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(
      const std::string& value);
  std::string* _internal_mutable_uuid();

  public:
  // string Card = 2;
  void clear_card() ;
  const std::string& card() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_card(Arg_&& arg, Args_... args);
  std::string* mutable_card();
  PROTOBUF_NODISCARD std::string* release_card();
  void set_allocated_card(std::string* value);

  private:
  const std::string& _internal_card() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_card(
      const std::string& value);
  std::string* _internal_mutable_card();

  public:
  // string CardHolderName = 4;
  void clear_cardholdername() ;
  const std::string& cardholdername() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cardholdername(Arg_&& arg, Args_... args);
  std::string* mutable_cardholdername();
  PROTOBUF_NODISCARD std::string* release_cardholdername();
  void set_allocated_cardholdername(std::string* value);

  private:
  const std::string& _internal_cardholdername() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cardholdername(
      const std::string& value);
  std::string* _internal_mutable_cardholdername();

  public:
  // string BankName = 5;
  void clear_bankname() ;
  const std::string& bankname() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_bankname(Arg_&& arg, Args_... args);
  std::string* mutable_bankname();
  PROTOBUF_NODISCARD std::string* release_bankname();
  void set_allocated_bankname(std::string* value);

  private:
  const std::string& _internal_bankname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bankname(
      const std::string& value);
  std::string* _internal_mutable_bankname();

  public:
  // int32 Sum = 3;
  void clear_sum() ;
  ::int32_t sum() const;
  void set_sum(::int32_t value);

  private:
  ::int32_t _internal_sum() const;
  void _internal_set_sum(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mid.GenerateInvoiceResponseFPSPostman)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      76, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GenerateInvoiceResponseFPSPostman& from_msg);
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    ::google::protobuf::internal::ArenaStringPtr card_;
    ::google::protobuf::internal::ArenaStringPtr cardholdername_;
    ::google::protobuf::internal::ArenaStringPtr bankname_;
    ::int32_t sum_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serv_2eproto;
};
// -------------------------------------------------------------------

class GenerateInvoiceRequestFPSPostman final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mid.GenerateInvoiceRequestFPSPostman) */ {
 public:
  inline GenerateInvoiceRequestFPSPostman() : GenerateInvoiceRequestFPSPostman(nullptr) {}
  ~GenerateInvoiceRequestFPSPostman() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GenerateInvoiceRequestFPSPostman* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GenerateInvoiceRequestFPSPostman));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GenerateInvoiceRequestFPSPostman(
      ::google::protobuf::internal::ConstantInitialized);

  inline GenerateInvoiceRequestFPSPostman(const GenerateInvoiceRequestFPSPostman& from) : GenerateInvoiceRequestFPSPostman(nullptr, from) {}
  inline GenerateInvoiceRequestFPSPostman(GenerateInvoiceRequestFPSPostman&& from) noexcept
      : GenerateInvoiceRequestFPSPostman(nullptr, std::move(from)) {}
  inline GenerateInvoiceRequestFPSPostman& operator=(const GenerateInvoiceRequestFPSPostman& from) {
    CopyFrom(from);
    return *this;
  }
  inline GenerateInvoiceRequestFPSPostman& operator=(GenerateInvoiceRequestFPSPostman&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GenerateInvoiceRequestFPSPostman& default_instance() {
    return *internal_default_instance();
  }
  static inline const GenerateInvoiceRequestFPSPostman* internal_default_instance() {
    return reinterpret_cast<const GenerateInvoiceRequestFPSPostman*>(
        &_GenerateInvoiceRequestFPSPostman_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(GenerateInvoiceRequestFPSPostman& a, GenerateInvoiceRequestFPSPostman& b) { a.Swap(&b); }
  inline void Swap(GenerateInvoiceRequestFPSPostman* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GenerateInvoiceRequestFPSPostman* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GenerateInvoiceRequestFPSPostman* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GenerateInvoiceRequestFPSPostman>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GenerateInvoiceRequestFPSPostman& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GenerateInvoiceRequestFPSPostman& from) { GenerateInvoiceRequestFPSPostman::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GenerateInvoiceRequestFPSPostman* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "mid.GenerateInvoiceRequestFPSPostman"; }

 protected:
  explicit GenerateInvoiceRequestFPSPostman(::google::protobuf::Arena* arena);
  GenerateInvoiceRequestFPSPostman(::google::protobuf::Arena* arena, const GenerateInvoiceRequestFPSPostman& from);
  GenerateInvoiceRequestFPSPostman(::google::protobuf::Arena* arena, GenerateInvoiceRequestFPSPostman&& from) noexcept
      : GenerateInvoiceRequestFPSPostman(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOrderTypeFieldNumber = 1,
    kSumFieldNumber = 2,
  };
  // .mid.OrderType orderType = 1;
  void clear_ordertype() ;
  ::mid::OrderType ordertype() const;
  void set_ordertype(::mid::OrderType value);

  private:
  ::mid::OrderType _internal_ordertype() const;
  void _internal_set_ordertype(::mid::OrderType value);

  public:
  // int32 Sum = 2;
  void clear_sum() ;
  ::int32_t sum() const;
  void set_sum(::int32_t value);

  private:
  ::int32_t _internal_sum() const;
  void _internal_set_sum(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:mid.GenerateInvoiceRequestFPSPostman)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GenerateInvoiceRequestFPSPostman& from_msg);
    int ordertype_;
    ::int32_t sum_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_serv_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GenerateRequestP2PPostman

// .mid.OrderType orderType = 1;
inline void GenerateRequestP2PPostman::clear_ordertype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ordertype_ = 0;
}
inline ::mid::OrderType GenerateRequestP2PPostman::ordertype() const {
  // @@protoc_insertion_point(field_get:mid.GenerateRequestP2PPostman.orderType)
  return _internal_ordertype();
}
inline void GenerateRequestP2PPostman::set_ordertype(::mid::OrderType value) {
  _internal_set_ordertype(value);
  // @@protoc_insertion_point(field_set:mid.GenerateRequestP2PPostman.orderType)
}
inline ::mid::OrderType GenerateRequestP2PPostman::_internal_ordertype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mid::OrderType>(_impl_.ordertype_);
}
inline void GenerateRequestP2PPostman::_internal_set_ordertype(::mid::OrderType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ordertype_ = value;
}

// int32 Sum = 2;
inline void GenerateRequestP2PPostman::clear_sum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sum_ = 0;
}
inline ::int32_t GenerateRequestP2PPostman::sum() const {
  // @@protoc_insertion_point(field_get:mid.GenerateRequestP2PPostman.Sum)
  return _internal_sum();
}
inline void GenerateRequestP2PPostman::set_sum(::int32_t value) {
  _internal_set_sum(value);
  // @@protoc_insertion_point(field_set:mid.GenerateRequestP2PPostman.Sum)
}
inline ::int32_t GenerateRequestP2PPostman::_internal_sum() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sum_;
}
inline void GenerateRequestP2PPostman::_internal_set_sum(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sum_ = value;
}

// -------------------------------------------------------------------

// GenerateResponseInvoiceP2PPostman

// string Uuid = 1;
inline void GenerateResponseInvoiceP2PPostman::clear_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& GenerateResponseInvoiceP2PPostman::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mid.GenerateResponseInvoiceP2PPostman.Uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GenerateResponseInvoiceP2PPostman::set_uuid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mid.GenerateResponseInvoiceP2PPostman.Uuid)
}
inline std::string* GenerateResponseInvoiceP2PPostman::mutable_uuid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:mid.GenerateResponseInvoiceP2PPostman.Uuid)
  return _s;
}
inline const std::string& GenerateResponseInvoiceP2PPostman::_internal_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uuid_.Get();
}
inline void GenerateResponseInvoiceP2PPostman::_internal_set_uuid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.Set(value, GetArena());
}
inline std::string* GenerateResponseInvoiceP2PPostman::_internal_mutable_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uuid_.Mutable( GetArena());
}
inline std::string* GenerateResponseInvoiceP2PPostman::release_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mid.GenerateResponseInvoiceP2PPostman.Uuid)
  return _impl_.uuid_.Release();
}
inline void GenerateResponseInvoiceP2PPostman::set_allocated_uuid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mid.GenerateResponseInvoiceP2PPostman.Uuid)
}

// string Card = 2;
inline void GenerateResponseInvoiceP2PPostman::clear_card() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_.ClearToEmpty();
}
inline const std::string& GenerateResponseInvoiceP2PPostman::card() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mid.GenerateResponseInvoiceP2PPostman.Card)
  return _internal_card();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GenerateResponseInvoiceP2PPostman::set_card(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mid.GenerateResponseInvoiceP2PPostman.Card)
}
inline std::string* GenerateResponseInvoiceP2PPostman::mutable_card() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_card();
  // @@protoc_insertion_point(field_mutable:mid.GenerateResponseInvoiceP2PPostman.Card)
  return _s;
}
inline const std::string& GenerateResponseInvoiceP2PPostman::_internal_card() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.card_.Get();
}
inline void GenerateResponseInvoiceP2PPostman::_internal_set_card(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_.Set(value, GetArena());
}
inline std::string* GenerateResponseInvoiceP2PPostman::_internal_mutable_card() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.card_.Mutable( GetArena());
}
inline std::string* GenerateResponseInvoiceP2PPostman::release_card() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mid.GenerateResponseInvoiceP2PPostman.Card)
  return _impl_.card_.Release();
}
inline void GenerateResponseInvoiceP2PPostman::set_allocated_card(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.card_.IsDefault()) {
    _impl_.card_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mid.GenerateResponseInvoiceP2PPostman.Card)
}

// int32 Sum = 3;
inline void GenerateResponseInvoiceP2PPostman::clear_sum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sum_ = 0;
}
inline ::int32_t GenerateResponseInvoiceP2PPostman::sum() const {
  // @@protoc_insertion_point(field_get:mid.GenerateResponseInvoiceP2PPostman.Sum)
  return _internal_sum();
}
inline void GenerateResponseInvoiceP2PPostman::set_sum(::int32_t value) {
  _internal_set_sum(value);
  // @@protoc_insertion_point(field_set:mid.GenerateResponseInvoiceP2PPostman.Sum)
}
inline ::int32_t GenerateResponseInvoiceP2PPostman::_internal_sum() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sum_;
}
inline void GenerateResponseInvoiceP2PPostman::_internal_set_sum(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sum_ = value;
}

// string CardHolderName = 4;
inline void GenerateResponseInvoiceP2PPostman::clear_cardholdername() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cardholdername_.ClearToEmpty();
}
inline const std::string& GenerateResponseInvoiceP2PPostman::cardholdername() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mid.GenerateResponseInvoiceP2PPostman.CardHolderName)
  return _internal_cardholdername();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GenerateResponseInvoiceP2PPostman::set_cardholdername(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cardholdername_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mid.GenerateResponseInvoiceP2PPostman.CardHolderName)
}
inline std::string* GenerateResponseInvoiceP2PPostman::mutable_cardholdername() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cardholdername();
  // @@protoc_insertion_point(field_mutable:mid.GenerateResponseInvoiceP2PPostman.CardHolderName)
  return _s;
}
inline const std::string& GenerateResponseInvoiceP2PPostman::_internal_cardholdername() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cardholdername_.Get();
}
inline void GenerateResponseInvoiceP2PPostman::_internal_set_cardholdername(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cardholdername_.Set(value, GetArena());
}
inline std::string* GenerateResponseInvoiceP2PPostman::_internal_mutable_cardholdername() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cardholdername_.Mutable( GetArena());
}
inline std::string* GenerateResponseInvoiceP2PPostman::release_cardholdername() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mid.GenerateResponseInvoiceP2PPostman.CardHolderName)
  return _impl_.cardholdername_.Release();
}
inline void GenerateResponseInvoiceP2PPostman::set_allocated_cardholdername(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cardholdername_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cardholdername_.IsDefault()) {
    _impl_.cardholdername_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mid.GenerateResponseInvoiceP2PPostman.CardHolderName)
}

// string BankName = 5;
inline void GenerateResponseInvoiceP2PPostman::clear_bankname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bankname_.ClearToEmpty();
}
inline const std::string& GenerateResponseInvoiceP2PPostman::bankname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mid.GenerateResponseInvoiceP2PPostman.BankName)
  return _internal_bankname();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GenerateResponseInvoiceP2PPostman::set_bankname(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bankname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mid.GenerateResponseInvoiceP2PPostman.BankName)
}
inline std::string* GenerateResponseInvoiceP2PPostman::mutable_bankname() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_bankname();
  // @@protoc_insertion_point(field_mutable:mid.GenerateResponseInvoiceP2PPostman.BankName)
  return _s;
}
inline const std::string& GenerateResponseInvoiceP2PPostman::_internal_bankname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bankname_.Get();
}
inline void GenerateResponseInvoiceP2PPostman::_internal_set_bankname(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bankname_.Set(value, GetArena());
}
inline std::string* GenerateResponseInvoiceP2PPostman::_internal_mutable_bankname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.bankname_.Mutable( GetArena());
}
inline std::string* GenerateResponseInvoiceP2PPostman::release_bankname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mid.GenerateResponseInvoiceP2PPostman.BankName)
  return _impl_.bankname_.Release();
}
inline void GenerateResponseInvoiceP2PPostman::set_allocated_bankname(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bankname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.bankname_.IsDefault()) {
    _impl_.bankname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mid.GenerateResponseInvoiceP2PPostman.BankName)
}

// -------------------------------------------------------------------

// GenerateInvoiceRequestFPSPostman

// .mid.OrderType orderType = 1;
inline void GenerateInvoiceRequestFPSPostman::clear_ordertype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ordertype_ = 0;
}
inline ::mid::OrderType GenerateInvoiceRequestFPSPostman::ordertype() const {
  // @@protoc_insertion_point(field_get:mid.GenerateInvoiceRequestFPSPostman.orderType)
  return _internal_ordertype();
}
inline void GenerateInvoiceRequestFPSPostman::set_ordertype(::mid::OrderType value) {
  _internal_set_ordertype(value);
  // @@protoc_insertion_point(field_set:mid.GenerateInvoiceRequestFPSPostman.orderType)
}
inline ::mid::OrderType GenerateInvoiceRequestFPSPostman::_internal_ordertype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mid::OrderType>(_impl_.ordertype_);
}
inline void GenerateInvoiceRequestFPSPostman::_internal_set_ordertype(::mid::OrderType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ordertype_ = value;
}

// int32 Sum = 2;
inline void GenerateInvoiceRequestFPSPostman::clear_sum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sum_ = 0;
}
inline ::int32_t GenerateInvoiceRequestFPSPostman::sum() const {
  // @@protoc_insertion_point(field_get:mid.GenerateInvoiceRequestFPSPostman.Sum)
  return _internal_sum();
}
inline void GenerateInvoiceRequestFPSPostman::set_sum(::int32_t value) {
  _internal_set_sum(value);
  // @@protoc_insertion_point(field_set:mid.GenerateInvoiceRequestFPSPostman.Sum)
}
inline ::int32_t GenerateInvoiceRequestFPSPostman::_internal_sum() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sum_;
}
inline void GenerateInvoiceRequestFPSPostman::_internal_set_sum(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sum_ = value;
}

// -------------------------------------------------------------------

// GenerateInvoiceResponseFPSPostman

// string Uuid = 1;
inline void GenerateInvoiceResponseFPSPostman::clear_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& GenerateInvoiceResponseFPSPostman::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mid.GenerateInvoiceResponseFPSPostman.Uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GenerateInvoiceResponseFPSPostman::set_uuid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mid.GenerateInvoiceResponseFPSPostman.Uuid)
}
inline std::string* GenerateInvoiceResponseFPSPostman::mutable_uuid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:mid.GenerateInvoiceResponseFPSPostman.Uuid)
  return _s;
}
inline const std::string& GenerateInvoiceResponseFPSPostman::_internal_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uuid_.Get();
}
inline void GenerateInvoiceResponseFPSPostman::_internal_set_uuid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.Set(value, GetArena());
}
inline std::string* GenerateInvoiceResponseFPSPostman::_internal_mutable_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uuid_.Mutable( GetArena());
}
inline std::string* GenerateInvoiceResponseFPSPostman::release_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mid.GenerateInvoiceResponseFPSPostman.Uuid)
  return _impl_.uuid_.Release();
}
inline void GenerateInvoiceResponseFPSPostman::set_allocated_uuid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mid.GenerateInvoiceResponseFPSPostman.Uuid)
}

// string Card = 2;
inline void GenerateInvoiceResponseFPSPostman::clear_card() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_.ClearToEmpty();
}
inline const std::string& GenerateInvoiceResponseFPSPostman::card() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mid.GenerateInvoiceResponseFPSPostman.Card)
  return _internal_card();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GenerateInvoiceResponseFPSPostman::set_card(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mid.GenerateInvoiceResponseFPSPostman.Card)
}
inline std::string* GenerateInvoiceResponseFPSPostman::mutable_card() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_card();
  // @@protoc_insertion_point(field_mutable:mid.GenerateInvoiceResponseFPSPostman.Card)
  return _s;
}
inline const std::string& GenerateInvoiceResponseFPSPostman::_internal_card() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.card_.Get();
}
inline void GenerateInvoiceResponseFPSPostman::_internal_set_card(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_.Set(value, GetArena());
}
inline std::string* GenerateInvoiceResponseFPSPostman::_internal_mutable_card() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.card_.Mutable( GetArena());
}
inline std::string* GenerateInvoiceResponseFPSPostman::release_card() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mid.GenerateInvoiceResponseFPSPostman.Card)
  return _impl_.card_.Release();
}
inline void GenerateInvoiceResponseFPSPostman::set_allocated_card(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.card_.IsDefault()) {
    _impl_.card_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mid.GenerateInvoiceResponseFPSPostman.Card)
}

// int32 Sum = 3;
inline void GenerateInvoiceResponseFPSPostman::clear_sum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sum_ = 0;
}
inline ::int32_t GenerateInvoiceResponseFPSPostman::sum() const {
  // @@protoc_insertion_point(field_get:mid.GenerateInvoiceResponseFPSPostman.Sum)
  return _internal_sum();
}
inline void GenerateInvoiceResponseFPSPostman::set_sum(::int32_t value) {
  _internal_set_sum(value);
  // @@protoc_insertion_point(field_set:mid.GenerateInvoiceResponseFPSPostman.Sum)
}
inline ::int32_t GenerateInvoiceResponseFPSPostman::_internal_sum() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sum_;
}
inline void GenerateInvoiceResponseFPSPostman::_internal_set_sum(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sum_ = value;
}

// string CardHolderName = 4;
inline void GenerateInvoiceResponseFPSPostman::clear_cardholdername() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cardholdername_.ClearToEmpty();
}
inline const std::string& GenerateInvoiceResponseFPSPostman::cardholdername() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mid.GenerateInvoiceResponseFPSPostman.CardHolderName)
  return _internal_cardholdername();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GenerateInvoiceResponseFPSPostman::set_cardholdername(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cardholdername_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mid.GenerateInvoiceResponseFPSPostman.CardHolderName)
}
inline std::string* GenerateInvoiceResponseFPSPostman::mutable_cardholdername() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cardholdername();
  // @@protoc_insertion_point(field_mutable:mid.GenerateInvoiceResponseFPSPostman.CardHolderName)
  return _s;
}
inline const std::string& GenerateInvoiceResponseFPSPostman::_internal_cardholdername() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cardholdername_.Get();
}
inline void GenerateInvoiceResponseFPSPostman::_internal_set_cardholdername(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cardholdername_.Set(value, GetArena());
}
inline std::string* GenerateInvoiceResponseFPSPostman::_internal_mutable_cardholdername() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cardholdername_.Mutable( GetArena());
}
inline std::string* GenerateInvoiceResponseFPSPostman::release_cardholdername() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mid.GenerateInvoiceResponseFPSPostman.CardHolderName)
  return _impl_.cardholdername_.Release();
}
inline void GenerateInvoiceResponseFPSPostman::set_allocated_cardholdername(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cardholdername_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cardholdername_.IsDefault()) {
    _impl_.cardholdername_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mid.GenerateInvoiceResponseFPSPostman.CardHolderName)
}

// string BankName = 5;
inline void GenerateInvoiceResponseFPSPostman::clear_bankname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bankname_.ClearToEmpty();
}
inline const std::string& GenerateInvoiceResponseFPSPostman::bankname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mid.GenerateInvoiceResponseFPSPostman.BankName)
  return _internal_bankname();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GenerateInvoiceResponseFPSPostman::set_bankname(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bankname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mid.GenerateInvoiceResponseFPSPostman.BankName)
}
inline std::string* GenerateInvoiceResponseFPSPostman::mutable_bankname() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_bankname();
  // @@protoc_insertion_point(field_mutable:mid.GenerateInvoiceResponseFPSPostman.BankName)
  return _s;
}
inline const std::string& GenerateInvoiceResponseFPSPostman::_internal_bankname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bankname_.Get();
}
inline void GenerateInvoiceResponseFPSPostman::_internal_set_bankname(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bankname_.Set(value, GetArena());
}
inline std::string* GenerateInvoiceResponseFPSPostman::_internal_mutable_bankname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.bankname_.Mutable( GetArena());
}
inline std::string* GenerateInvoiceResponseFPSPostman::release_bankname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mid.GenerateInvoiceResponseFPSPostman.BankName)
  return _impl_.bankname_.Release();
}
inline void GenerateInvoiceResponseFPSPostman::set_allocated_bankname(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bankname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.bankname_.IsDefault()) {
    _impl_.bankname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mid.GenerateInvoiceResponseFPSPostman.BankName)
}

// -------------------------------------------------------------------

// GenerateRequestPayoutPostman

// .mid.OrderType orderType = 1;
inline void GenerateRequestPayoutPostman::clear_ordertype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ordertype_ = 0;
}
inline ::mid::OrderType GenerateRequestPayoutPostman::ordertype() const {
  // @@protoc_insertion_point(field_get:mid.GenerateRequestPayoutPostman.orderType)
  return _internal_ordertype();
}
inline void GenerateRequestPayoutPostman::set_ordertype(::mid::OrderType value) {
  _internal_set_ordertype(value);
  // @@protoc_insertion_point(field_set:mid.GenerateRequestPayoutPostman.orderType)
}
inline ::mid::OrderType GenerateRequestPayoutPostman::_internal_ordertype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::mid::OrderType>(_impl_.ordertype_);
}
inline void GenerateRequestPayoutPostman::_internal_set_ordertype(::mid::OrderType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ordertype_ = value;
}

// int32 sum = 2;
inline void GenerateRequestPayoutPostman::clear_sum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sum_ = 0;
}
inline ::int32_t GenerateRequestPayoutPostman::sum() const {
  // @@protoc_insertion_point(field_get:mid.GenerateRequestPayoutPostman.sum)
  return _internal_sum();
}
inline void GenerateRequestPayoutPostman::set_sum(::int32_t value) {
  _internal_set_sum(value);
  // @@protoc_insertion_point(field_set:mid.GenerateRequestPayoutPostman.sum)
}
inline ::int32_t GenerateRequestPayoutPostman::_internal_sum() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sum_;
}
inline void GenerateRequestPayoutPostman::_internal_set_sum(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sum_ = value;
}

// string card = 3;
inline void GenerateRequestPayoutPostman::clear_card() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_.ClearToEmpty();
}
inline const std::string& GenerateRequestPayoutPostman::card() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mid.GenerateRequestPayoutPostman.card)
  return _internal_card();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GenerateRequestPayoutPostman::set_card(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mid.GenerateRequestPayoutPostman.card)
}
inline std::string* GenerateRequestPayoutPostman::mutable_card() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_card();
  // @@protoc_insertion_point(field_mutable:mid.GenerateRequestPayoutPostman.card)
  return _s;
}
inline const std::string& GenerateRequestPayoutPostman::_internal_card() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.card_.Get();
}
inline void GenerateRequestPayoutPostman::_internal_set_card(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_.Set(value, GetArena());
}
inline std::string* GenerateRequestPayoutPostman::_internal_mutable_card() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.card_.Mutable( GetArena());
}
inline std::string* GenerateRequestPayoutPostman::release_card() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mid.GenerateRequestPayoutPostman.card)
  return _impl_.card_.Release();
}
inline void GenerateRequestPayoutPostman::set_allocated_card(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.card_.IsDefault()) {
    _impl_.card_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mid.GenerateRequestPayoutPostman.card)
}

// -------------------------------------------------------------------

// GenerateResponsePayoutPostman

// int32 id = 1;
inline void GenerateResponsePayoutPostman::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
}
inline ::int32_t GenerateResponsePayoutPostman::id() const {
  // @@protoc_insertion_point(field_get:mid.GenerateResponsePayoutPostman.id)
  return _internal_id();
}
inline void GenerateResponsePayoutPostman::set_id(::int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:mid.GenerateResponsePayoutPostman.id)
}
inline ::int32_t GenerateResponsePayoutPostman::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void GenerateResponsePayoutPostman::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// string uuid = 2;
inline void GenerateResponsePayoutPostman::clear_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& GenerateResponsePayoutPostman::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mid.GenerateResponsePayoutPostman.uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GenerateResponsePayoutPostman::set_uuid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mid.GenerateResponsePayoutPostman.uuid)
}
inline std::string* GenerateResponsePayoutPostman::mutable_uuid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:mid.GenerateResponsePayoutPostman.uuid)
  return _s;
}
inline const std::string& GenerateResponsePayoutPostman::_internal_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uuid_.Get();
}
inline void GenerateResponsePayoutPostman::_internal_set_uuid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.Set(value, GetArena());
}
inline std::string* GenerateResponsePayoutPostman::_internal_mutable_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uuid_.Mutable( GetArena());
}
inline std::string* GenerateResponsePayoutPostman::release_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mid.GenerateResponsePayoutPostman.uuid)
  return _impl_.uuid_.Release();
}
inline void GenerateResponsePayoutPostman::set_allocated_uuid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:mid.GenerateResponsePayoutPostman.uuid)
}

// bool success = 3;
inline void GenerateResponsePayoutPostman::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
}
inline bool GenerateResponsePayoutPostman::success() const {
  // @@protoc_insertion_point(field_get:mid.GenerateResponsePayoutPostman.success)
  return _internal_success();
}
inline void GenerateResponsePayoutPostman::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:mid.GenerateResponsePayoutPostman.success)
}
inline bool GenerateResponsePayoutPostman::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void GenerateResponsePayoutPostman::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace mid


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::mid::OrderType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::mid::OrderType>() {
  return ::mid::OrderType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // serv_2eproto_2epb_2eh
