// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: serv.proto

package files

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Api_GenerateInvoiceP2P_FullMethodName = "/mid.Api/GenerateInvoiceP2P"
	Api_GenerateInvoiceFPS_FullMethodName = "/mid.Api/GenerateInvoiceFPS"
	Api_GeneratePayout_FullMethodName     = "/mid.Api/GeneratePayout"
)

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	GenerateInvoiceP2P(ctx context.Context, in *GenerateRequestP2PPostman, opts ...grpc.CallOption) (*GenerateResponseInvoiceP2PPostman, error)
	GenerateInvoiceFPS(ctx context.Context, in *GenerateInvoiceRequestFPSPostman, opts ...grpc.CallOption) (*GenerateInvoiceResponseFPSPostman, error)
	GeneratePayout(ctx context.Context, in *GenerateRequestPayoutPostman, opts ...grpc.CallOption) (*GenerateResponsePayoutPostman, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) GenerateInvoiceP2P(ctx context.Context, in *GenerateRequestP2PPostman, opts ...grpc.CallOption) (*GenerateResponseInvoiceP2PPostman, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponseInvoiceP2PPostman)
	err := c.cc.Invoke(ctx, Api_GenerateInvoiceP2P_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GenerateInvoiceFPS(ctx context.Context, in *GenerateInvoiceRequestFPSPostman, opts ...grpc.CallOption) (*GenerateInvoiceResponseFPSPostman, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateInvoiceResponseFPSPostman)
	err := c.cc.Invoke(ctx, Api_GenerateInvoiceFPS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GeneratePayout(ctx context.Context, in *GenerateRequestPayoutPostman, opts ...grpc.CallOption) (*GenerateResponsePayoutPostman, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponsePayoutPostman)
	err := c.cc.Invoke(ctx, Api_GeneratePayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility.
type ApiServer interface {
	GenerateInvoiceP2P(context.Context, *GenerateRequestP2PPostman) (*GenerateResponseInvoiceP2PPostman, error)
	GenerateInvoiceFPS(context.Context, *GenerateInvoiceRequestFPSPostman) (*GenerateInvoiceResponseFPSPostman, error)
	GeneratePayout(context.Context, *GenerateRequestPayoutPostman) (*GenerateResponsePayoutPostman, error)
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServer struct{}

func (UnimplementedApiServer) GenerateInvoiceP2P(context.Context, *GenerateRequestP2PPostman) (*GenerateResponseInvoiceP2PPostman, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateInvoiceP2P not implemented")
}
func (UnimplementedApiServer) GenerateInvoiceFPS(context.Context, *GenerateInvoiceRequestFPSPostman) (*GenerateInvoiceResponseFPSPostman, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateInvoiceFPS not implemented")
}
func (UnimplementedApiServer) GeneratePayout(context.Context, *GenerateRequestPayoutPostman) (*GenerateResponsePayoutPostman, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePayout not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}
func (UnimplementedApiServer) testEmbeddedByValue()             {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	// If the following call pancis, it indicates UnimplementedApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_GenerateInvoiceP2P_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequestP2PPostman)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GenerateInvoiceP2P(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GenerateInvoiceP2P_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GenerateInvoiceP2P(ctx, req.(*GenerateRequestP2PPostman))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GenerateInvoiceFPS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateInvoiceRequestFPSPostman)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GenerateInvoiceFPS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GenerateInvoiceFPS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GenerateInvoiceFPS(ctx, req.(*GenerateInvoiceRequestFPSPostman))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GeneratePayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequestPayoutPostman)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GeneratePayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GeneratePayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GeneratePayout(ctx, req.(*GenerateRequestPayoutPostman))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mid.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateInvoiceP2P",
			Handler:    _Api_GenerateInvoiceP2P_Handler,
		},
		{
			MethodName: "GenerateInvoiceFPS",
			Handler:    _Api_GenerateInvoiceFPS_Handler,
		},
		{
			MethodName: "GeneratePayout",
			Handler:    _Api_GeneratePayout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serv.proto",
}
